
= M2 Repository

== 2.0.0
* Moved Plugin from com.buschmais.jqassistant.plugin (core-Distribution) to org.jqassistant.plugin

== 1.12.0
* Implemented propagation of dependencies which are declared by a model (i.e. pom.xml) to the described main artifact. This allows queries to determine (transitive) dependencies between artifacts, e.g.
+
----
MATCH
  (platform:Artifact)
WHERE
  platform.fqn="jakarta.platform:jakarta.jakartaee-api:jar:9.1.0"
MATCH
  (platform)-[dependsOn:DEPENDS_ON*]->(dependency:Artifact)
RETURN
  *
----

== 1.7.0

* Improved repository scanner to correctly handle SNAPSHOTS and build up a hierarchical GAV structure
* Download artifacts from repository in background while scanning to improve performance
* Default value of property `m2repo.artifacts.scan` changed to `false`, i.e. only models are scanned by default

== 1.3

* Only internal changes.

== 1.2

* Maven coordinates changed from `com.buschmais.jqassistant.plugin:jqassistant.plugin.m2repo`
  to `com.buschmais.jqassistant.plugin:m2repo`.
* No functional changes since version 1.1.3.



