jqassistant:
  plugins:
    - group-id: ${it.plugin.groupId}
      artifact-id: ${it.plugin.artifactId}
      version: ${it.plugin.version}
  scan:
    include:
      urls:
        - maven:repository::https://repo1.maven.org/maven2
    properties:
      m2repo.filter.includes: jakarta.*:*:*
      m2repo.directory: ${it.m2repo.directory}
  analyze:
    groups:
      - it
